[[redirects]]
  from = "/hero/*"
  to = "/404/hero.html"
  status = 404

[[redirects]]
  from = "/about/*"
  to = "/404/about.html"
  status = 404

[[redirects]]
  from = "/projects/*"
  to = "/404/projects.html"
  status = 404

[[redirects]]
  from = "/contact/*"
  to = "/404/contact.html"
  status = 404
